package com.example.spring.admin.controller;

import com.example.spring.admin.model.Admin;
import com.example.spring.admin.repository.AdminRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@CrossOrigin(origins = "*")
@RestController
@RequestMapping(path = "admin/user")
public class AdminController {


    // Aggregate root
    // tag::get-aggregate-root[]
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AdminRepository adminRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Admin admin = new Admin();
        admin.setName(name);
        admin.setEmail(email);
        adminRepository.save(admin);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Admin> getAllUsers() {
        // This returns a JSON or XML with the users
        return adminRepository.findAll();
    }
}
